EmployeeDashboard/urls.py
from django.conf.urls import url
from . import views as v

#set the NAMESPACE
app_name='EmployeeDashboard'

urlpatterns = [
       url(r'emp_auth/$',v.emp_auth,name='emp_auth'),
       url(r'employee_dashboard/$',v.employee_dashboard,name='employee_dashboard'),
       url(r'add_reminder/$',v.add_reminder,name='add_reminder'),
       url(r'emp_assign_work/$',v.emp_assign_work,name='emp_assign_work'),
       url(r'report_work/$',v.report_work,name='report_work'),
       url(r'(?P<id>\d+)/emp_work_detail/$',v.emp_work_detail,name='emp_work_detail'),

       ]

RayAdvisors/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from AdminDashboard import views
from front import views as f
from EmployeeDashboard import views as v

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', f.index,name='index'),
    url(r'^site_admin/',include('AdminDashboard.urls')),
    url(r'^employee/',include('EmployeeDashboard.urls')),
    url(r'^SearchCompany/',include('Search_Company.urls',namespace='Search_Company')),
    url(r'^front/',include('front.urls')),
    url(r'^special/',views.special,name='special'),
    url(r'^$',views.user_logout,name='logout'),
    url(r'^special/',v.special,name='special'),
    url(r'^$',v.user_logout,name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

front/urls.py
from django.conf.urls import url
from front import views
# from AdminDashboard import views as v

app_name = 'front'

urlpatterns = [
                # url(r'^$', v.index_post_list,name='index_post_list'),
                url(r'^$', views.index,name='index'),
               
                url(r'new1/$',views.new1,name='new1'),
                url(r'new2/$',views.new2,name='new2'),
                url(r'new3/$',views.new3,name='new3'),
                url(r'new4/$',views.new4,name='new4'),
                url(r'new5/$',views.new5,name='new5'),
                url(r'new7/$',views.new7,name='new7'),
                url(r'new8/$',views.new8,name='new8'),
                url(r'new9/$',views.new9,name='new9'),
                url(r'new10/$',views.new10,name='new10'),
                url(r'about/$',views.about,name='about'),
                url(r'(?P<id>\d+)/post_detail/$',views.post_detail,name='post_detail'),
                url(r'feedback/$',views.feedback,name='feedback'),
               ]

EmployeeDashboard/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# from AdminDashboard.models import AdminProfile
# from RayAdvisors.AdminDashboard.models import AdminProfile

# Create your models here.
#EMPLOYEE PROFILE
class EmployeeProfile(models.Model):
    user = models.OneToOneField(User)
    admin_name = models.ForeignKey('AdminDashboard.AdminProfile',default=1)
    email = models.EmailField(max_length=50,default=None)
    emp_name = models.CharField(max_length=30)
    contact_no = models.PositiveIntegerField()
    location = models.CharField(max_length=50)
    image = models.ImageField(upload_to='profile_pics/employee/', blank=True)  

    def __str__(self):
         return self.user.username

    def get_absolute_url(self):
        return reverse("AdminDashboard:emp_edit", kwargs={"id": self.id})
 

class EmployeeReminder(models.Model):
    emp_name = models.ForeignKey(EmployeeProfile, on_delete = models.CASCADE, default=1)
    content = models.CharField(max_length=100)
    date = models.DateField(default=timezone.now)

    def __str__(self):
        return self.content
    
    class Meta:
        ordering = ["-date"]



#reporting of work
class ReportWork(models.Model):
    admin_name = models.ForeignKey('AdminDashboard.AdminProfile', on_delete = models.CASCADE, default=1)
    emp_name = models.ForeignKey('EmployeeProfile', on_delete = models.CASCADE, default=1)
    work_title=models.ForeignKey('AdminDashboard.WorkAssign',default=1,on_delete=models.CASCADE,related_name='ewtitle')
    work_progress=models.CharField(max_length=20)
    reason=models.TextField(blank=True,default=None)
    report_date=models.DateField(default=timezone.now)

    def __unicode__(self):
        return self.work_progress

    def __str__(self):
        return self.work_progress

EmployeeDashboard/forms.py
from django import forms
from django.contrib.auth.models import User
from EmployeeDashboard.models import EmployeeProfile,ReportWork,EmployeeReminder

#employee profile form
class EmployeeProfileForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))

    class Meta():
        model=User
        fields=('username','password')
        widgets = {
            'username': forms.TextInput(attrs={'class':'form-control'}),
        }

#employee profile form for extra fields
class EmployeeProfileInfoForm(forms.ModelForm):
    class Meta():
        model = EmployeeProfile
        fields = ('emp_name','email','contact_no','location','image')
        widgets = {
            'emp_name': forms.TextInput(attrs={'class':'form-control'}),
            'email': forms.EmailInput(attrs={'class':'form-control'}),
            'contact_no': forms.NumberInput(attrs={'class':'form-control'}),
            'location': forms.TextInput(attrs={'class':'form-control'}),
        }


class EmployeeReminderForm(forms.ModelForm):
    class Meta():
        model = EmployeeReminder
        fields=('content',)



#employee work reporting form
class ReportWorkInfoForm(forms.ModelForm):
    class Meta():
        model=ReportWork
        fields=('work_title','work_progress','reason')        



EmployeeDashboard/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404, redirect
from EmployeeDashboard.forms import EmployeeProfileForm,EmployeeProfileInfoForm,ReportWorkInfoForm,EmployeeReminderForm


from django.template import RequestContext

#imports for login & logout
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.contrib.auth.decorators import login_required




from .models import EmployeeProfile,EmployeeReminder,ReportWork
from AdminDashboard.models import WorkAssign

# Create your views here.

# EMPlOYEE SECTION  
#login view
def emp_auth(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return employee_dashboard(request)
            else:
                return HttpResponse("Your account is not active.")

        else:
            print("someone tried to login and failed")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied")

    else:
        return render(request, 'employee_login.html',{}) 

        
#decorators for login
@login_required
def special(request):
    return HttpResponse("you are logged in.")


@login_required  
def user_logout(request):
    logout(request)
    return index(request)
          
     

def employee_dashboard(request,emp_name=None):
    current_user = request.user.employeeprofile
    print(current_user)
    queryset = EmployeeReminder.objects.filter(emp_name=current_user).order_by('-date')

    work_len = WorkAssign.objects.filter(emp_name=current_user)
    wlength=len(work_len)

    report_len = ReportWork.objects.filter(emp_name=current_user)
    rlength=len(report_len)
    context = {
        "reminder_list": queryset,
        "wlength":wlength,
        "rlength":rlength,
    }
    return render(request,"employee_dashboard.html",context)  


def add_reminder(request):
    registered = False
    if request.method == 'POST':
        reminder_form = EmployeeReminderForm(data=request.POST)
        if reminder_form.is_valid():
            instance=reminder_form.save(commit=False)
            instance.emp_name=request.user.employeeprofile
            instance.save()
           
            registered =True
            return HttpResponseRedirect("/employee/employee_dashboard")
        else:
            print(reminder_form.errors)
    else:
        reminder_form = EmployeeReminderForm()

    return render(request,'employee_dashboard.html',
                        {'reminder_form':reminder_form,
                        'registered':registered})




#list of assigned works
def emp_assign_work(request, emp_name=None):
    current_user = request.user.employeeprofile
    queryset = WorkAssign.objects.filter(emp_name=current_user)
    # print(current_user)
    # print(queryset)
    context = {
        "object_list": queryset,
         }
    return render(request,'emp_assign_work.html',context)   

def emp_work_detail(request, id=None):
    instance = get_object_or_404(WorkAssign, id=id)
    context ={
        "instance":instance,
    }
    return render(request,"emp_work_detail.html",context)     


def report_work(request, emp_name=None):
    current_user = request.user.employeeprofile
    queryset = WorkAssign.objects.filter(emp_name=current_user)
    context = {
        "work_list": queryset,
    }
    registered = False
    if request.method == 'POST':
        report_form = ReportWorkInfoForm(data=request.POST)
        if report_form.is_valid():
            instance = report_form.save(commit=False)
            instance.emp_name = current_user
            instance.save()
            registered = True
            return HttpResponseRedirect("/employee/employee_dashboard")
        else:
            print(report_form.errors)
    else:
        report_form = ReportWorkInfoForm()
       
    return render(request,'report_work.html',
                        {'report_form':report_form,
                        'registered':registered, 
                        "work_list": queryset})

EmployeeDashboard/templates/emp_assign_work.html
{% extends "employee_dashboard.html" %}
{% block body_block1 %}

<h3 class="title-3">Assigned Work</h3> 
<div class="table-data__tool">
  <div class="table-responsive table-responsive-data2">
    <table class="table table-data2">
      <thead>
        <tr>
          <th>S.No</th>
          <th>WORK TITLE</th>
          <th>assigned DATE</th>
        </tr>
      </thead>
      <tbody>
        {% for p in object_list %}
        <tr class="tr-shadow">
          <td>{{ forloop.counter }}</td>
          <td>{{ p.work_title }}</td>
          <td>{{ p.work_date }}</td>
          <td>
            <div class="table-data-feature">
              <a href='{% url "EmployeeDashboard:emp_work_detail" id=p.id %}' class="item" data-toggle="modal" data-target="#myModal" data-placement="top" role="button" title="View Work">
              <i class="fa fa-eye"></i>
              </a>
            </div>
          </td>
        </tr>
        <!-- modal to view the work content -->
       <!--  
        <div class="modal fade" id="myModal" role="dialog">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Work description</h4>
              </div>
              <div class="modal-body">
                <p>{{ p.work_content }}</p>
              </div>
             <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div> -->
        <div class="modal fade" id="myModal" role="dialog">
          <div class="modal-dialog modal-lg">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title text-center form-title">Work Description</h4>
              </div>
              <div class="modal-body padtrbl">
                <div class="login-box-body">
                  <h5>{{ p.work_content }}</h5>
                </div>
              </div>
            </div>
          </div>
        </div>

      {% endfor %}
    </tbody>
  </table>
</div>
</div>
{% endblock %}




{% block body_block2 %}


<li class="list-inline-item">Assigned Work</li>


{% endblock %}




{% block body_block3 %}
<li>
  <a href="{% url 'EmployeeDashboard:employee_dashboard' %}">
    <i class="fas fa-tachometer-alt"></i>Dashboard</a>
  </li>


  <li class="active">
    <a  href="{% url 'EmployeeDashboard:emp_assign_work' %}">
      <i class="fa fa-tasks"></i>Assigned Work
    </a>
  </li>

  <li>
    <a href="{% url 'EmployeeDashboard:report_work' %}">
      <i class="fa fa-book"></i>Report Work
    </a>
  </li>

  {% endblock %}

EmployeeDashboard/templates/emp_work_detail.html
{% extends "employee_dashboard.html" %}
{% block body_block1 %}

<h3 class="title-3">View Work</h3> <br>
  <div class="container">
    <div class="jumbotron">
      <h1 class="mt-2">{{ instance.work_title }}</h1>

        <p class="lead">
        assigned on
          <a href="#">{{ instance.work_date }}</a>
        </p>
      <hr>
      <p>{{ instance.work_content}}
     
    </div>
  </div>
 {% endblock %}


  {% block body_block2 %}
    <li class="list-inline-item">Assigned Work</li>
  {% endblock %}




        {% block body_block3 %}
                        <li>
                            <a href="{% url 'EmployeeDashboard:employee_dashboard' %}">
                                <i class="fas fa-tachometer-alt"></i>Dashboard</a>
                        </li>


                        <li class="active">
                            <a  href="{% url 'EmployeeDashboard:emp_assign_work' %}">
                                <i class="fa fa-tasks"></i>Assigned Work
                            </a>
                        </li>

                        <li>
                            <a href="{% url 'EmployeeDashboard:report_work' %}">
                                <i class="fa fa-book"></i>Report Work
                            </a>
                        </li>
                        
    {% endblock %}

EmployeeDashboard/templates/employee_dashboard.html
{% extends "emp_dashbaord_base.html" %}
{% load staticfiles %}
{% block body_block1 %}
<div class="row">
    <div class="col-lg-6">
        <div class="au-card au-card--no-shadow au-card--no-pad m-b-40">
            <div class="au-card-title" style="background-image:url({% static 'images/bg-title-01.jpg' %});">
                <div class="bg-overlay bg-overlay--blue"></div>
                
                <div class="noti__item js-item-menu" >
                    <h3><i class="zmdi zmdi-plus" ></i>Create Reminders..</h3>
                    <div class="mess-dropdown js-dropdown" >
                        <div class="mess__item">
                            <div class="content" >
                                <form method="POST" action="{% url 'EmployeeDashboard:add_reminder' %}" enctype="multipart/form-data">
                                    <div class="form-group" >
                                        {% csrf_token %}
                                        <label for="id_content">Reminder:</label>
                                        <textarea id="id_content" class="form-control" maxlength="100" name="content" type="text" required ></textarea>
                                    </div>
                                    <div class="form-group">
                                        <input type="submit" class="btn btn-success" value="Add">
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>               
            </div> 
            <div class="au-task js-list-load">
               <div class="au-task-list js-scrollbar3">

                <div class="au-task__item au-task__item--success">
                    {% for rem in reminder_list %}
                    <div class="au-task__item-inner">
                        <h5 class="task">
                            <a href="#">{{ rem.content }}</a>
                        </h5>
                        <span class="time">{{ rem.date }}</span>
                    </div>
                    {% endfor %}
                </div>  

            </div>
            <div class="au-task__footer">
                <button class="au-btn au-btn-load js-load-btn">load more</button>
            </div>
        </div> 
    </div>
    <div>

    </div> 


</div>

<div class="col-lg-6">
    <div class="overview-item overview-item--c1">
        <div class="overview__inner">
            <div class="overview-box clearfix">
                <div class="icon">
                    <i class="zmdi zmdi-account-o"></i>
                </div>
                <div class="text">
                    <h2>{{ wlength }}</h2>
                    <span>Total Work Assigned</span>
                </div>
            </div>
            <div class="overview-chart">
                <canvas id="widgetChart1"></canvas>
            </div>
        </div>
    </div>
    <div class="overview-item overview-item--c3">
        <div class="overview__inner">
            <div class="overview-box clearfix">
                <div class="icon">
                    <i class="zmdi zmdi-calendar-note"></i>
                </div>
                <div class="text">
                    <h2>{{ rlength }}</h2>
                    <span>Total Work Reported</span>
                </div>
            </div>
            <div class="overview-chart">
                <canvas id="widgetChart3"></canvas>
            </div>
        </div>
    </div>
</div>


</div>  
{% endblock %}

    {% block body_block2 %}
        <li class="list-inline-item">Dashboard</li>
    {% endblock %}

    {% block body_block3 %}
                        <li class="active">
                            <a href="{% url 'EmployeeDashboard:employee_dashboard' %}">
                                <i class="fas fa-tachometer-alt"></i>Dashboard</a>
                        </li>


                        <li>
                            <a  href="{% url 'EmployeeDashboard:emp_assign_work' %}">
                                <i class="fa fa-tasks"></i>Assigned Work
                            </a>
                        </li>

                        <li>
                            <a href="{% url 'EmployeeDashboard:report_work' %}">
                                <i class="fa fa-book"></i>Report Work
                            </a>
                        </li>
                        
    {% endblock %}

EmployeeDashboard/templates/employee_login.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <!-- Title Page-->
    <title>Employee Login</title>

    <!-- Fontfaces CSS-->
    <link rel="stylesheet" href="{% static "css/font-face.css" %}" />
    <link href="{% static "vendor/font-awesome-4.7/css/font-awesome.min.css" %}" rel="stylesheet" media="all">
    <link href="{% static "vendor/font-awesome-5/css/fontawesome-all.min.css" %}" rel="stylesheet" media="all">
    <link href="{% static "vendor/mdi-font/css/material-design-iconic-font.min.css" %}" rel="stylesheet" media="all">

    <!-- Bootstrap CSS-->
    <link href="{% static "vendor/bootstrap-4.1/bootstrap.min.css" %}" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{% static "css/theme.css" %}" rel="stylesheet" media="all">

    <!-- Vendor CSS-->
    <link href="{% static "vendor/animsition/animsition.min.css" %}" rel="stylesheet" media="all">
    <link href="{% static "vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css" %}" rel="stylesheet" media="all">
    <link href="{% static "vendor/wow/animate.css" %}" rel="stylesheet" media="all">
    <link href="{% static "vendor/css-hamburgers/hamburgers.min.css" %}" rel="stylesheet" media="all">
    <link href="{% static "vendor/slick/slick.css" %}" rel="stylesheet" media="all">
    <link href="{% static "vendor/select2/select2.min.css" %}" rel="stylesheet" media="all">
    <link href="{% static "vendor/perfect-scrollbar/perfect-scrollbar.css" %}" rel="stylesheet" media="all">
</head>
<body>
    <div class="page-wrapper">
        <div class="page-content--bge5">
            <div class="container">
                <div class="login-wrap">
                    <div class="login-content">
                        <div class="login-logo">
                            <a href="#">
                                <img src="{% static "images/user_logo.jpg" %}" height="150" width="150" alt="CoolAdmin">
                            </a>
                        </div>
                        <div class="login-form">
                            <form action="{% url 'EmployeeDashboard:emp_auth' %}" method="POST">
                                {% csrf_token %}
                               <div class="form-group">
                                    <label>Username</label>
                                    <input class="au-input au-input--full" type="text" name="username" placeholder="Username" required>
                                </div>
                                <div class="form-group">
                                    <label>Password</label>
                                    <input class="au-input au-input--full" type="password" name="password" placeholder="Password" required>
                                </div> 
                                <br>
                                <button class="au-btn au-btn--block au-btn--green m-b-20" type="submit">sign in</button>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

</body>
</html>

EmployeeDashboard/templates/report_work.html
{% extends "employee_dashboard.html" %}
{% block body_block1 %}
<h3 class="title-3">Report Assigned Work</h3>
<br>
<form class="form-horizontal" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
{{ form.non_field_errors }}
    <div class="form-group">
        {{ report_form.work_title.errors }}
        <label for="{{ report_form.work_title.id_for_label }}" class="control-label col-xs-2">*Assigned Work Title:</label>
        <div class="col-xs-10">  
            <select id="id_work_title"  class="form-control" name="work_title" required="">
                <option value="" disabled="" selected="selected">--SELECT--</option>
                {% for w in work_list %}
                <option value="{{ w.id }}">{{ w.work_title }}</option>
                {% endfor %}
            </select>         
        </div>
    </div>

    <div class="form-group">
        {{ report_form.work_progress.errors }}
        <label for="{{ report_form.work_progress.id_for_label }}" class="control-label col-xs-2">*Status:</label>
        <div class="col-xs-10">
            <select id="id_work_progress"  class="form-control" name="work_progress" required="">
                <option value="" disabled="" selected="selected">--SELECT--</option>
                <option value="Done">Done</option>
                <option value="Pending">Pending</option>
               
            </select>         
        </div>
    </div>

    <div class="form-group">
        {{ report_form.reason.errors }}
       <label for="{{ report_form.reason.id_for_label }}" class="control-label col-xs-2">*Reason:</label>
        <div class="col-xs-10"> 
            <textarea type="text" rows=5 class="form-control" name="reason" placeholder="You can type NA if the work is done..else type your reason if the work is pending... " ></textarea>
        </div>
    </div>

    <div class="form-group">
        <div class="col-xs-offset-2 col-xs-10">
        <input type="submit" class="btn btn-primary" value="Report Work">
        </div>
    </div>
</form>
{% endblock %}



{% block body_block2 %}
<li class="list-inline-item">Report Work</li>
{% endblock %}



{% block body_block3 %}
<li>
    <a href="{% url 'EmployeeDashboard:employee_dashboard' %}">
        <i class="fas fa-tachometer-alt"></i>Dashboard</a>
    </li>


    <li>
        <a  href="{% url 'EmployeeDashboard:emp_assign_work' %}">
            <i class="fa fa-tasks"></i>Assigned Work
        </a>
    </li>

    <li class="active">
        <a href="{% url 'EmployeeDashboard:report_work' %}">
            <i class="fa fa-book"></i>Report Work
        </a>
    </li>

    {% endblock %}