AdminDashboard/urls.py
from django.conf.urls import url
from AdminDashboard import views


#set the NAMESPACE
app_name='AdminDashboard'

urlpatterns = [
       url(r'test/$',views.test,name='test'),
       url(r'dashboard/$',views.dashboard,name='dashboard'),
       url(r'add_reminder/$',views.add_reminder,name='add_reminder'),
       url(r'login/$',views.user_login,name='user_login'),
       url(r'reg/$',views.reg,name='reg'),
       url(r'create/$',views.post_create,name='add_post'),
       url(r'(?P<id>\d+)/$',views.post_detail,name='detail'),
       url(r'^posts/',views.post_list,name='all_posts'),
       url(r'(?P<id>\d+)/edit/$',views.post_update,name='update'),
       url(r'(?P<id>\d+)/delete/$',views.post_delete,name="delete"),
       url(r'(?P<id>\d+)/emp_edit/$',views.emp_edit,name='emp_edit'),
       url(r'(?P<id>\d+)/emp_delete/$',views.emp_delete,name="emp_delete"),
       url(r'allposts/$',views.all_posts_list,name='allp'),
       url(r'all_employees/$',views.all_employees,name='all_employees'),
       url(r'assign_work/$',views.assign_work,name='assign_work'),
       url(r'(?P<id>\d+)/work_detail/$',views.work_detail,name='work_detail'),
       url(r'(?P<id>\d+)/track_emp_reason/$',views.track_emp_reason,name='track_emp_reason'),
       url(r'add_employee/$',views.add_employee,name='add_employee'),
       url(r'track_emp_detail/$',views.track_emp_detail,name='track_emp_detail'),
       url(r'track_emp_list/$',views.track_emp_list,name='track_emp_list'),
       url(r'feedback/$',views.feedback,name='feedback'),
       url(r'(?P<id>\d+)/feedback_delete/$',views.feedback_delete,name="feedback_delete"),
       url(r'(?P<id>\d+)/feedback_detail/$',views.feedback_detail,name='feedback_detail'),
]

RayAdvisors/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from AdminDashboard import views
from front import views as f
from EmployeeDashboard import views as v

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', f.index,name='index'),
    url(r'^site_admin/',include('AdminDashboard.urls')),
    url(r'^employee/',include('EmployeeDashboard.urls')),
    url(r'^SearchCompany/',include('Search_Company.urls',namespace='Search_Company')),
    url(r'^front/',include('front.urls')),
    url(r'^special/',views.special,name='special'),
    url(r'^$',views.user_logout,name='logout'),
    url(r'^special/',v.special,name='special'),
    url(r'^$',v.user_logout,name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

front/urls.py
from django.conf.urls import url
from front import views
# from AdminDashboard import views as v

app_name = 'front'

urlpatterns = [
                # url(r'^$', v.index_post_list,name='index_post_list'),
                url(r'^$', views.index,name='index'),
               
                url(r'new1/$',views.new1,name='new1'),
                url(r'new2/$',views.new2,name='new2'),
                url(r'new3/$',views.new3,name='new3'),
                url(r'new4/$',views.new4,name='new4'),
                url(r'new5/$',views.new5,name='new5'),
                url(r'new7/$',views.new7,name='new7'),
                url(r'new8/$',views.new8,name='new8'),
                url(r'new9/$',views.new9,name='new9'),
                url(r'new10/$',views.new10,name='new10'),
                url(r'about/$',views.about,name='about'),
                url(r'(?P<id>\d+)/post_detail/$',views.post_detail,name='post_detail'),
                url(r'feedback/$',views.feedback,name='feedback'),
               ]

AdminDashboard/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.conf import settings
from django.utils import timezone
# from EmployeeDashboard.models import EmployeeProfile


# Create your models here.

#ADMIN PROFILE 
class AdminProfile(models.Model):
    user=models.OneToOneField(User)
    image = models.ImageField(upload_to='profile_pics/admin/', blank=True)

    def __str__(self):
         return self.user.username


#admin reminder
class AdminReminder(models.Model):
    admin_name = models.ForeignKey(AdminProfile, on_delete = models.CASCADE, default=1)
    content = models.CharField(max_length=100)
    date = models.DateField(auto_now=False, auto_now_add=False,default=timezone.now)
    
    
    class Meta:
        ordering = ["-date"]

    def __str__(self):
        return self.content    

#work assignment to employee
class WorkAssign(models.Model):
    admin_name = models.ForeignKey(AdminProfile, on_delete = models.CASCADE, default=1)
    emp_name=models.ForeignKey('EmployeeDashboard.EmployeeProfile',default=1,on_delete=models.CASCADE)
    work_title=models.CharField(max_length=50)
    work_content=models.CharField(max_length=500)
    work_date=models.DateField(default=timezone.now)


    def __str__(self):
        return self.work_title


#Admin blogging
def upload_location(instance, filename):
    return "%s/%s" %(instance.id, filename)

class AdminPost(models.Model):
    author = models.ForeignKey(AdminProfile, default=1)
    title=models.CharField(max_length=256)
    slug = models.SlugField(unique=True)
    image=models.ImageField(null=True, blank=True,
                            width_field="width_field", 
                            height_field="height_field",
                            upload_to="upload_location")
    width_field = models.IntegerField(default=0)
    height_field = models.IntegerField(default=0)
    content=models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateTimeField(auto_now=False, auto_now_add=False,default=timezone.now)
    updated=models.DateTimeField(auto_now=True,auto_now_add=False)
    timestamp=models.DateTimeField(auto_now=False,auto_now_add=True)

    def __unicode__(self):
        return self.title
        
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("AdminDashboard:detail", kwargs={"id": self.id})

    class Meta:
        ordering = ["-timestamp","-updated"]

def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug= new_slug
    qs = AdminPost.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug

def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_save_post_receiver, sender=AdminPost)

AdminDashboard/views.py
from django.shortcuts import render
from django.contrib.auth.models import User

from django.shortcuts import render, get_object_or_404, redirect
from AdminDashboard.forms import (AdminProfileForm, AdminProfileInfoForm, 
                                    EmployeeWorkAssignForm,AdminPostForm,AdminReminderForm)

from EmployeeDashboard.forms import EmployeeProfileForm,EmployeeProfileInfoForm
from django.template import RequestContext
from django.contrib import messages

#imports for login & logout
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.contrib.auth.decorators import login_required

#imports for blogging
from django.utils import timezone
from django.db.models import Q
from django.core.urlresolvers import reverse,reverse_lazy

from .models import AdminPost,WorkAssign,AdminReminder
from EmployeeDashboard.models import EmployeeProfile,ReportWork
from front.models import Feedback


def test(request):
    return render(request,"test.html")

# Create your views here.
def index(request):
    return render(request,"index.html")

#registration view
def reg(request):
    registered = False
    if request.method == 'POST':
        user_form = AdminProfileForm(data=request.POST)
        profile_form = AdminProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'image' in request.FILES:
                print('found it')
                profile.image = request.FILES['image']
            profile.save()
            registered = True
            return index(request)

        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = AdminProfileForm()
        profile_form = AdminProfileInfoForm()

    return render(request,'reg.html',
                        {'user_form':user_form,
                        'profile_form':profile_form,
                        'registered':registered})

#login view
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect("/site_admin/dashboard")
            else:
                return HttpResponse("Your account is not active.")

        else:
            print("someone tried to login and failed")
            print("They used username: {} and password: {}".format(username,password))
            context={"msg":"Invalid login details supplied"}
            print(context)
            return render(request, 'login.html',context) 
    else:
        return render(request, 'login.html', {})   
        
#decorators for login
@login_required
def special(request):
    return HttpResponse("you are logged in.")


@login_required  
def user_logout(request):
    logout(request)
    return index(request)


#to land on dashboard
def dashboard(request,admin_name=None):
    current_user = request.user.adminprofile
    queryset = AdminReminder.objects.filter(admin_name=current_user)
    emp_len = EmployeeProfile.objects.all()
    emp_length = len(emp_len)
    current_user = request.user.adminprofile
    post_len = AdminPost.objects.filter(author=current_user,draft=False)
    post_length=len(post_len)
    context = {
        "reminder_list": queryset,
        "elength":emp_length,
        "plength":post_length,
    }


    return render(request,'dashboard.html',context)


def add_reminder(request):
    registered = False
    if request.method == 'POST':
        reminder_form = AdminReminderForm(data=request.POST)

        print(reminder_form)
        if reminder_form.is_valid():
            instance=reminder_form.save(commit=False)
            instance.admin_name=request.user.adminprofile
            instance.save()
            registered =True
            return HttpResponseRedirect("/site_admin/dashboard")
        else:
            print(reminder_form.errors)
    else:
        reminder_form = AdminReminderForm()

    return render(request,'dashboard.html',
                        {'reminder_form':reminder_form,
                        'registered':registered})

    



def add_employee(request):
    print("hello")
    registered = False
    if request.method == 'POST':
        emp_form = EmployeeProfileForm(data=request.POST)
        profile_form = EmployeeProfileInfoForm(data=request.POST)
   
        if emp_form.is_valid() and profile_form.is_valid():
            user = emp_form.save(commit=False)
            user.set_password(user.password)
            user.admin_name = request.user.adminprofile
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'image' in request.FILES:
                print('found it')
                profile.image = request.FILES['image']
            profile.save()
            registered = True
            return HttpResponseRedirect("/site_admin/dashboard")

        else:
            print(emp_form.errors,profile_form.errors)

    else:
        emp_form = EmployeeProfileForm()
        profile_form = EmployeeProfileInfoForm()
       

    return render(request,'add_employee.html',
                        {'emp_form':emp_form,
                        'profile_form':profile_form,
                        'registered':registered})

def all_employees(request):
    queryset = EmployeeProfile.objects.all()
    length = len(queryset)
    print(length)
    context = {
        "object_list": queryset,
    }

    return render(request,'all_employees.html',context)


def emp_edit(request, id=None):
    print("hello")
    emp = get_object_or_404(EmployeeProfile, id=id)
   
    if request.method == 'POST':
        profile_form = EmployeeProfileInfoForm(request.POST or None, instance=emp)
        try:
            if profile_form.is_valid():
                profile_form.save()
                messages.success(request,'Employee profile is successfully updated')
                return HttpResponseRedirect("/site_admin/dashboard")
            else:
                print(emp_form.errors)
        except Exception as e:
            messages.warning(request,"Employee didn't saved. {}".format(e))
    
    else:
        profile_form = EmployeeProfileInfoForm(instance=emp)

        context = {
            "emp": emp,
            "profile_form": profile_form,
        }
    
    return render(request,"add_employee.html", context)

def emp_delete(request, id=None):
    instance = get_object_or_404(EmployeeProfile, id=id)
    instance.delete()
    return redirect("AdminDashboard:all_employees")    



def assign_work(request):
    queryset = EmployeeProfile.objects.all()
    context = {
        "emp_list": queryset,
    }
    registered = False
    if request.method == 'POST':        
        work_form = EmployeeWorkAssignForm(data=request.POST)
        if work_form.is_valid():
            work_form.save()
            registered = True
            return HttpResponseRedirect("/site_admin/dashboard")
        else:
            print(work_form.errors)
    else:
        work_form = EmployeeWorkAssignForm()
    return render(request,'assign_work.html',
                        {'work_form':work_form,
                        'registered':registered, 
                        "emp_list": queryset})


def work_detail(request, id=None):
    instance = get_object_or_404(WorkAssign, id=id)
    context ={
        "instance":instance,
    }
    return render(request,"work_detail.html",context)


def track_emp_list(request):
    queryset= WorkAssign.objects.all()
    context = {
        "emp_list": queryset,
    }
    return render(request,"track_emp_list.html",context)


def track_emp_detail(request):
    queryset = ReportWork.objects.all()
    context = {
        "emp_list":queryset,
    }
    return render(request,"track_employee.html",context)


def track_emp_reason(request,id=None):
    instance = get_object_or_404(ReportWork, id=id)
    context ={
        "instance":instance,
    }
    
    return render(request,"track_emp_reason.html",context)


#Blogging views
#post creation view
def post_create(request):
    template = 'add_post.html'
    form = AdminPostForm(request.POST or None, request.FILES or None)
    try:
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user.adminprofile
            instance.save()
            messages.success(request,'Post created successfully!')
            return HttpResponseRedirect("/site_admin/dashboard")
    except Exception as e:
        messages.warning(request,"Post didn't saved")
    context = {
        "form": form,
    }
    return render(request, template, context)

#list of posts
def post_list(request,author=None):
    current_user = request.user.adminprofile
    queryset = AdminPost.objects.filter(author=current_user)
    context = {
        "object_list": queryset,
        "title": "List"
    }
    return render(request,"all_posts.html",context)


#details of post
def post_detail(request, id=None):
    instance = get_object_or_404(AdminPost, id=id)
    context = {
        "title": instance.title,
        "instance": instance,
    }
    return render(request, "post_detail.html", context)


#post edit view
def post_update(request, id=None):
    post = get_object_or_404(AdminPost, id=id)

    if request.method == 'POST':
        form = AdminPostForm(request.POST or None, request.FILES or None, instance=post)

        try:
            if form.is_valid():
                form.save()
                messages.success(request,'Blog is successfully updated')

AdminDashboard/templates/all_employees.html
{% extends "dashboard_base.html" %}
{% block body_block1 %}
<h3 class="title-3">All employees</h3> <br>
<div class="table-data__tool">


  <div class="table-responsive table-responsive-data2">
    <table class="table table-data2">
      <thead>
        <tr>
          <th>S.No.</th>
          <th>Employee name</th>
          <th>Email Id</th>
          <th>Contact no</th>
          <th>Location</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
       
        {% for p in object_list %} 
          <td>{{ forloop.counter }}</td>
          <td>{{ p.emp_name }}</td>
          <td>{{ p.email }}</td> 
          <td>{{ p.contact_no }}</td>
          <td>{{ p.location }}</td>
          <td>
            <div class="table-data-feature">
              
             
              <a href='{% url "AdminDashboard:emp_edit" id=p.id %}'  class="item" data-toggle="tooltip" data-placement="top" role="button" title="Edit">
                <i class="zmdi zmdi-edit"></i>
              </a>
              
              <a href='{% url "AdminDashboard:emp_delete" id=p.id %}' class="item" data-toggle="tooltip" data-placement="top" role="button" title="Delete">
                <i class="zmdi zmdi-delete"></i>
              </a>

            </div>
          </td>
        </tr>
        <tr class="spacer"></tr>
        {% endfor %}
        
        
      </tbody>
    </table>
    {% endblock %}




    {% block body_block2 %}
    <li class="list-inline-item">All Employees</li>
    {% endblock %}




    {% block body_block3 %}
    <li>
      <a href="{% url 'AdminDashboard:dashboard' %}">
        <i class="fas fa-tachometer-alt"></i>Dashboard</a>
      </li>


      <li>
        <a  href="{% url 'AdminDashboard:add_employee' %}">
          <i class="fa fa-user-plus"></i>Add Employee
        </a>
      </li>

      <li class="active">
        <a href="{% url 'AdminDashboard:all_employees' %}">
          <i class="fa fa-group"></i>All Employees</a>
        </li>
        <li>
          <a href="{% url 'AdminDashboard:assign_work' %}">
            <i class="fa fa-tasks"></i>Assign Work</a>
          </li>
          <li>
            <a href="{% url 'AdminDashboard:track_emp_list' %}">
              <i class="fa fa-map-marker"></i>Track Employees</a>
            </li>
            <li class="has-sub">
              <a class="js-arrow" href="#">
                <i class="fas fa-copy"></i>Blogs
                <span class="arrow">
                  <i class="fas fa-angle-down"></i>
                </span>
              </a>
              <ul class="list-unstyled navbar__sub-list js-sub-list">
                <li class="active">
                  <a href="{% url 'AdminDashboard:add_post' %}">
                    <i class="fas fa-user"></i>Add New Post</a>
                  </li>
                  <li>
                    <a href="{% url 'AdminDashboard:all_posts' %}">
                      <i class="fas fa-sign-in-alt"></i>All Posts</a>
                    </li>
                  </ul>
                   <li>
                                  <a href="{% url 'AdminDashboard:feedback' %}">
                                    <i class="fa fa-pencil-square-o"></i>Feedback</a>
                                </li>
                </li>
               
                  {% endblock %}

AdminDashboard/templates/all_posts.html
{% extends "dashboard.html" %}
{% block body_block1 %}

<h3 class="title-3">All Posts</h3> 
<div class="table-data__tool">
  <div class="table-responsive table-responsive-data2">
    <table class="table table-data2">
      <thead>
        <tr>
          <th>S.No.</th>
          <th>TITLE</th>
          <th>AUTHOR</th>
          <th>STATUS</th>
          <th>PUBLISHED</th>  
        </tr>
      </thead>

      <tbody>
        {% for p in object_list %}
        <tr class="tr-shadow">
          <td>{{ forloop.counter }}</td>
          <td>{{ p.title }}</td>
          <td>{{ p.author }}</td>
          {% if p.draft %}
            <td><span style='color:red;'>Draft</span></td>
          {% elif p.publish %}
            <td><span style='color:green;'>Published</span></td>
          {% endif %}
          <td>{{ p.publish}}</td>
          <td>
            <div class="table-data-feature">
              <a href='{{ p.get_absolute_url }}' class="item" data-toggle="tooltip" data-placement="top" role="button" title="View" target="_blank">
                <i class="fa fa-eye"></i>
              </a>

              <a href='{% url "AdminDashboard:update" id=p.id %}' class="item" data-toggle="tooltip" data-placement="top" role="button" title="Edit" >
                <i class="zmdi zmdi-edit"></i>
              </a>
              <a href='{% url "AdminDashboard:delete" id=p.id %}' class="item" data-toggle="tooltip" data-placement="top" role="button" title="Delete" >
                <i class="zmdi zmdi-delete"></i>
              </a>
            </div>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}




      {% block body_block2 %}
      <li class="list-inline-item">Posts</li>
      <li class="list-inline-item seprate">
        <span>/</span>

        <li class="list-inline-item">All Posts</li>


        {% endblock %}




        {% block body_block3 %}
                        <li >
                            <a href="{% url 'AdminDashboard:dashboard' %}">
                                <i class="fas fa-tachometer-alt"></i>Dashboard</a>
                        </li>


                        <li>
                            <a  href="{% url 'AdminDashboard:add_employee' %}">
                                <i class="fa fa-user-plus"></i>Add Employee
                            </a>
                        </li>

                        <li>
                            <a href="{% url 'AdminDashboard:all_employees' %}">
                                <i class="fa fa-group"></i>All Employees</a>
                        </li>
                        <li>
                            <a href="{% url 'AdminDashboard:assign_work' %}">
                                <i class="fa fa-tasks"></i>Assign Work</a>
                        </li>
                        <li>
                            <a href="{% url 'AdminDashboard:track_emp_list' %}">
                                <i class="fa fa-map-marker"></i>Track Employees</a>
                        </li>
                        <li class="has-sub">
                            <a class="js-arrow" href="#">
                                <i class="fas fa-copy"></i>Blogs
                                <span class="arrow">
                                    <i class="fas fa-angle-down"></i>
                                </span>
                            </a>
                            <ul class="list-unstyled navbar__sub-list js-sub-list">
                                <li>
                                    <a href="{% url 'AdminDashboard:add_post' %}">
                                        <i class="fas fa-user"></i>Add New Post</a>
                                </li>
                                <li class="active">
                                    <a href="{% url 'AdminDashboard:all_posts' %}">
                                        <i class="fas fa-sign-in-alt"></i>All Posts</a>
                                </li>
                            </ul>
                             <li>
                                  <a href="{% url 'AdminDashboard:feedback' %}">
                                    <i class="fa fa-pencil-square-o"></i>Feedback</a>
                                </li>
                        </li>
                       
    {% endblock %}

AdminDashboard/templates/dashboard.html
{% extends "dashboard_base.html" %}
{% load staticfiles %}
{% block body_block1 %}

<div class="row">
    <div class="col-lg-6">
        <div class="au-card au-card--no-shadow au-card--no-pad m-b-40">
            <div class="au-card-title" style="background-image:url({% static 'images/bg-title-01.jpg' %});">
                <div class="bg-overlay bg-overlay--blue"></div>
                
                <div class="noti__item js-item-menu" >
                    <h3><i class="zmdi zmdi-plus" ></i>Create Reminders..</h3>
                    <div class="mess-dropdown js-dropdown" >
                        <div class="mess__item">
                            <div class="content" >
                                <form method="POST" action="{% url 'AdminDashboard:add_reminder' %}" enctype="multipart/form-data">
                                    <div class="form-group" >
                                        {% csrf_token %}
                                        <label for="id_content">Reminder:</label>
                                        <textarea id="id_content" class="form-control" maxlength="100" name="content" type="text" required ></textarea>
                                    </div>
                                    <div class="form-group">
                                        <input type="submit" class="btn btn-success" value="Add">
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>               
            </div> 
            <div class="au-task js-list-load">
               <div class="au-task-list js-scrollbar3">

                <div class="au-task__item au-task__item--success">
                    {% for rem in reminder_list %}
                    <div class="au-task__item-inner">
                        <h5 class="task">
                            <a href="#">{{ rem.content }}</a>
                        </h5>
                        <span class="time">{{ rem.date }}</span>
                    </div>
                    {% endfor %}
                </div>  

            </div>
            <div class="au-task__footer">
                <button class="au-btn au-btn-load js-load-btn">load more</button>
            </div>
        </div> 
    </div>
    <div>

    </div> 


</div>

<div class="col-lg-6">
    <div class="overview-item overview-item--c1">
        <div class="overview__inner">
            <div class="overview-box clearfix">
                <div class="icon">
                    <i class="zmdi zmdi-account-o"></i>
                </div>
                <div class="text">
                    <h2>{{ elength }}</h2>
                    <span> Total Working Employees</span>
                </div>
            </div>
            <div class="overview-chart">
                <canvas id="widgetChart1"></canvas>
            </div>
        </div>
    </div>
    <div class="overview-item overview-item--c3">
        <div class="overview__inner">
            <div class="overview-box clearfix">
                <div class="icon">
                    <i class="zmdi zmdi-calendar-note"></i>
                </div>
                <div class="text">
                    <h2>{{ plength }}</h2>
                    <span>Posts Published By You Till Now</span>
                </div>
            </div>
            <div class="overview-chart">
                <canvas id="widgetChart3"></canvas>
            </div>
        </div>
    </div>
</div>


</div>



{% endblock %}



{% block body_block2 %}

<li class="list-inline-item">Dashboard</li>


{% endblock %}

{% block body_block3 %}
<li class="active">
    <a href="{% url 'AdminDashboard:dashboard' %}">
        <i class="fas fa-tachometer-alt"></i>Dashboard</a>
    </li>

    <li>
        <a  href="{% url 'AdminDashboard:add_employee' %}">
            <i class="fa fa-user-plus"></i>Add Employee
        </a>
    </li>

    <li>
        <a href="{% url 'AdminDashboard:all_employees' %}">
            <i class="fa fa-group"></i>All Employees
        </a>
    </li>

    <li>
        <a href="{% url 'AdminDashboard:assign_work' %}">
            <i class="fa fa-tasks"></i>Assign Work</a>
        </li>
        <li>
            <a href="{% url 'AdminDashboard:track_emp_list' %}">
                <i class="fa fa-map-marker"></i>Track Employees</a>
            </li>
            <li class="has-sub">
                <a class="js-arrow" href="#">
                    <i class="fas fa-copy"></i>Blogs
                    <span class="arrow">
                        <i class="fas fa-angle-down"></i>
                    </span>
                </a>
                <ul class="list-unstyled navbar__sub-list js-sub-list">
                    <li>
                        <a href="{% url 'AdminDashboard:add_post' %}">
                            <i class="fas fa-user"></i>Add New Post</a>
                        </li>
                        <li>
                            <a href="{% url 'AdminDashboard:all_posts' %}">
                                <i class="fas fa-sign-in-alt"></i>All Posts</a>
                            </li>
                        </ul>
                        <li>
                          <a href="{% url 'AdminDashboard:feedback' %}">
                            <i class="fa fa-pencil-square-o"></i>Feedback</a>
                        </li>
                    </li>

                    {% endblock %}

AdminDashboard/templates/posts_page.html
{% extends 'base.html' %}
{% block body_block %}
{% load staticfiles %}



<link href="{% static "layout-1/css/styles.css" %}" rel="stylesheet">

<link href="{% static "layout-1/css/responsive.css" %}" rel="stylesheet">
<hr>
<div class="col-xs-12 col-md-6">
  <form action="" method="GET" class="form-main  form-inline nofloat-xs pull-right pull-left-sm">

    <div class="form-group form-input-fields form-group-lg has-feedback">

      <label class="sr-only" for="search">Search</label>
      <div class="input-group">
        <input type="text" class="form-control input-search" name="q" value='{{ request.GET.q }}' placeholder="Search">
      </div>

      <button type="submit" class="btn btn-lg btn-success btn-submit">
       Search 
     </button>


   </div>


 </form>
</div>
</div> 
<section class="blog-area section">
  <div class="container">
    <div class="row">
      {% for p in object_list %}
      <div class="col-lg-4 col-md-6">
        
        <div class="card h-100">
          
          <div class="single-post post-style-1">

            <h4 class="title"><b>{{ p.title }}</b></h4>
            <a class="btn btn-primary" href="{{ p.get_absolute_url }}" target="_blank"><b>VIEW POST</b></a>

          </div><!-- single-post -->
          
        </div><!-- card -->

      </div><!-- col-lg-4 col-md-6 -->
      {% endfor %}
    </div>
  </div>
</section>


{% endblock %}


