AdminDashboard/urls.py
from django.conf.urls import url
from AdminDashboard import views


#set the NAMESPACE
app_name='AdminDashboard'

urlpatterns = [
       url(r'test/$',views.test,name='test'),
       url(r'dashboard/$',views.dashboard,name='dashboard'),
       url(r'add_reminder/$',views.add_reminder,name='add_reminder'),
       url(r'login/$',views.user_login,name='user_login'),
       url(r'reg/$',views.reg,name='reg'),
       url(r'create/$',views.post_create,name='add_post'),
       url(r'(?P<id>\d+)/$',views.post_detail,name='detail'),
       url(r'^posts/',views.post_list,name='all_posts'),
       url(r'(?P<id>\d+)/edit/$',views.post_update,name='update'),
       url(r'(?P<id>\d+)/delete/$',views.post_delete,name="delete"),
       url(r'(?P<id>\d+)/emp_edit/$',views.emp_edit,name='emp_edit'),
       url(r'(?P<id>\d+)/emp_delete/$',views.emp_delete,name="emp_delete"),
       url(r'allposts/$',views.all_posts_list,name='allp'),
       url(r'all_employees/$',views.all_employees,name='all_employees'),
       url(r'assign_work/$',views.assign_work,name='assign_work'),
       url(r'(?P<id>\d+)/work_detail/$',views.work_detail,name='work_detail'),
       url(r'(?P<id>\d+)/track_emp_reason/$',views.track_emp_reason,name='track_emp_reason'),
       url(r'add_employee/$',views.add_employee,name='add_employee'),
       url(r'track_emp_detail/$',views.track_emp_detail,name='track_emp_detail'),
       url(r'track_emp_list/$',views.track_emp_list,name='track_emp_list'),
       url(r'feedback/$',views.feedback,name='feedback'),
       url(r'(?P<id>\d+)/feedback_delete/$',views.feedback_delete,name="feedback_delete"),
       url(r'(?P<id>\d+)/feedback_detail/$',views.feedback_detail,name='feedback_detail'),
]

EmployeeDashboard/urls.py
from django.conf.urls import url
from . import views as v

#set the NAMESPACE
app_name='EmployeeDashboard'

urlpatterns = [
       url(r'emp_auth/$',v.emp_auth,name='emp_auth'),
       url(r'employee_dashboard/$',v.employee_dashboard,name='employee_dashboard'),
       url(r'add_reminder/$',v.add_reminder,name='add_reminder'),
       url(r'emp_assign_work/$',v.emp_assign_work,name='emp_assign_work'),
       url(r'report_work/$',v.report_work,name='report_work'),
       url(r'(?P<id>\d+)/emp_work_detail/$',v.emp_work_detail,name='emp_work_detail'),

       ]

RayAdvisors/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from AdminDashboard import views
from front import views as f
from EmployeeDashboard import views as v

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', f.index,name='index'),
    url(r'^site_admin/',include('AdminDashboard.urls')),
    url(r'^employee/',include('EmployeeDashboard.urls')),
    url(r'^SearchCompany/',include('Search_Company.urls',namespace='Search_Company')),
    url(r'^front/',include('front.urls')),
    url(r'^special/',views.special,name='special'),
    url(r'^$',views.user_logout,name='logout'),
    url(r'^special/',v.special,name='special'),
    url(r'^$',v.user_logout,name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Search_Company/urls.py
from django.conf.urls import url
from Search_Company import views

app_name='Search_Company'

urlpatterns = [
    url(r'^$',views.search_company,name='search_company'),
    url(r'^search$', views.search, name='search'),
    url(r'^company$', views.fetch_company_data, name='company'),
]

front/urls.py
from django.conf.urls import url
from front import views
# from AdminDashboard import views as v

app_name = 'front'

urlpatterns = [
                # url(r'^$', v.index_post_list,name='index_post_list'),
                url(r'^$', views.index,name='index'),
               
                url(r'new1/$',views.new1,name='new1'),
                url(r'new2/$',views.new2,name='new2'),
                url(r'new3/$',views.new3,name='new3'),
                url(r'new4/$',views.new4,name='new4'),
                url(r'new5/$',views.new5,name='new5'),
                url(r'new7/$',views.new7,name='new7'),
                url(r'new8/$',views.new8,name='new8'),
                url(r'new9/$',views.new9,name='new9'),
                url(r'new10/$',views.new10,name='new10'),
                url(r'about/$',views.about,name='about'),
                url(r'(?P<id>\d+)/post_detail/$',views.post_detail,name='post_detail'),
                url(r'feedback/$',views.feedback,name='feedback'),
               ]

front/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Feedback(models.Model):
    name=models.CharField(max_length=50)
    email=models.EmailField()
    message=models.TextField()
    date = models.DateField(default=timezone.now)

    def __str__(self):
        return self.name

    class Meta:
        ordering =["-date"]

front/forms.py
from django import forms
from . models import Feedback

#admin profile form for User
class FeedbackForm(forms.ModelForm):

    class Meta():
        model=Feedback
        fields=('name','email','message')

front/views.py
from django.shortcuts import render
from AdminDashboard.models import AdminPost
from django.utils import timezone
from django.shortcuts import render, get_object_or_404
from front.forms import FeedbackForm
from django.http import HttpResponseRedirect

# Create your views here.
def index(request):
    queryset=AdminPost.objects.filter(draft=False).filter(publish__lte=timezone.now())[:5]
    context={
    "object_list":queryset,
    "title":"List"
    }
    
    return render(request,"index.html",context)
   
def new1(request):
    return render(request,"new1.html")

def new2(request):
    return render(request,"new2.html")    

def new3(request):
    return render(request,"new3.html")

def new4(request):
    return render(request,"new4.html")

def new5(request):
    return render(request,"new5.html")

def new7(request):
    return render(request,"new7.html")   

def new8(request):
    return render(request,"new8.html")    

def new9(request):
    return render(request,"new9.html")

def new10(request):
    return render(request,"new10.html")    


def about(request):
    return render(request,"about.html")          

def post_detail(request, id=None):
    instance = get_object_or_404(AdminPost, id=id)
    context = {
        "title": instance.title,
        "instance": instance,
    }
    return render(request, "post_detail.html", context)

def feedback(request):
    
    if request.method == 'POST':
        feedback_form = FeedbackForm(request.POST)
        

        if feedback_form.is_valid():
            feedback_form.save()
            return HttpResponseRedirect("/")

        else:
            print(feedback_form.errors)

    else:
        feedback_form = FeedbackForm()
       

    return render(request,'index.html',
                        {'feedback_form':feedback_form})

front/templates/about.html
{% extends "base.html" %}
{% block body_block %}
{% load staticfiles %}

    <section id="fh5co-about" data-section="about">
        <div class="container">
            <div class="row">
                <div class="col-md-12 section-heading text-center">
                    <h2 class="to-animate">About Us </h2>
                    <div class="row">
                        <div class="col-md-8 col-md-offset-2 subtext to-animate">
                            <h3>Our weary eyes still stray to the horizon. Though down this road we've been so many times.</h3>
                        </div>
                    </div>
                </div>
            </div>
           
            <br><br>
            <div class="row">
                <div class="col-md-4">
                    <div class="fh5co-person text-center to-animate">
                        <figure><img src="{% static "assets/images/about/img2.png" %}" alt="Image"></figure>
                        <h3>Yogesh Maheshwari</h3>
                        <span class="fh5co-position">Company Secretary</span><br><br><br>
                        <p class="contwvr">Yogesh Maheshwari did his Graduation in Commerce from University of Delhi and an Associate Member of Institute of Company Secretaries of India. He has 3 years of experience in matters related to company formation, Secretarial Audit, internal/statutory audit, tax and regulatory services, financial and business advisory, compliances under company law, registration of IPRs, liaison with various authorities for registrations, supervision and training of interns etc. He is also associated with reputed organizations as legal advisor.</p>

                    </div>
                </div>
                <div class="col-md-4">
                    <div class="fh5co-person text-center to-animate">
                        <figure><img src="{% static "assets/images/about/img.png" %}" alt="Image"></figure>
                        <h3>Rahul Malhotra</h3>
                        <span class="fh5co-position">Company Secretary</span><br><br><br>
                        <p class="contwvr">CS Rahul Malhotra did his graduation in commerce from University of Delhi and an associative member of an institution of Company Secretaries of India.He also holds Bachelor of Laws (LL.B.) from University of Delhi.He has a post qualification experience of 3 years and manages the company law  compliances of clients.He is actively engaged in multi-disciplinary practices including corporate secretarial and governance services,appearances before various tribunals and/or any other quasi-judicial body,Secretarial Audit,internal/statutory audit,tax and regulatory services,financial and business advisory.He is also associated with reputed organizations as legal advisor.</p>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="fh5co-person text-center to-animate">
                        <figure><img src="{% static "assets/images/about/img1.png" %}" alt="Image"></figure>
                        <h3>Akanksha Maheshwari</h3>
                        <span class="fh5co-position">Company Secretary</span><br><br><br>
                        <p class="contwvr">Akanksha Maheshwari did his Graduation in Commerce from University of Delhi and an Associate Member of Institute of Company Secretaries of India. She also holds Bachelor of Laws (LL.B.) from University of Delhi. She has a post qualification experience of 3 years in corporate laws including FDI, Securities Laws, Setting-up companies, Corporate Governance for listed entities, due diligence audits, Overall compliance monitoring etc. She also brings experience in the areas of legal due diligence, Secretarial Audit, rendering opinion on Companies Act and other Corporate Laws, processing various petitions/applications with NCLT/MCA.</p></p>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

front/templates/base.html
{% load staticfiles %}

<!doctype html>
<html class="no-js" lang=""> 
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RAY Advisors LLP</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" href="apple-touch-icon.png">
    
   <!--  for blog post -->
    <link href="{% static "css/blog-post.css" %}" rel="stylesheet">
    <!--Google fonts links-->
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i" rel="stylesheet">
    <link rel="stylesheet" href="{% static "assets/css/bootstrap.min.css" %}">


        <!--For Plugins external css-->
        <link rel="stylesheet" href="{% static "assets/css/plugins.css" %}" />
        <link rel="stylesheet" href="{% static "assets/css/roboto-webfont.css" %}" />

        <!--Theme custom css -->
        <link rel="stylesheet" href="{% static "assets/css/style.css" %}">
        <link rel="stylesheet" href="{% static "assets/css/modal.css" %}">

        <!--Theme Responsive css-->
        <link rel="stylesheet" href="{% static "assets/css/responsive.css" %}" />
        <script src="{% static "assets/js/vendor/modernizr-2.8.3-respond-1.4.2.min.js" %}"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

        <!-- validating admin id -->
         <script>
         $(document).ready(function(){
           $("#btnSaveIt").click(function(){
            $id="admin"
              if($('#admin_id').val()==$id){
              $("#modal1").attr("data-target", "#select");
           }
           else
           {
             $("#select").hide();
             $("#modal1").attr("data-target", "#"); 
             alert("Enter a valid id"); 
           }
         });
         })
       </script>
  </head>
  <body>
          <nav class="navbar navbar-default">
            <div class="container">
              <!-- Brand and oggle get grouped for better mobile display -->
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url "index" %}"><img src="{% static "assets/images/logo.jpg" %}" alt="Logo" style="padding-top:0px; width: 197px" /></a>
              </div>

              <!-- Collect the nav links, forms, and other content for toggling -->
              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

                <ul class="nav navbar-nav navbar-right">
                  <li><a href="{% url "index" %}">Home</a></li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Acts and Rules <i class="fa fa-caret-down"></i>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown" style ="background-color:#6e727a; width: 300px" >
                      <p class="navla"><a class="dropdown-item" target="_blank" href="http://www.mca.gov.in/Ministry/pdf/ProvisionsTable_CompAct.pdf" style="color:white; font-size:14px;">Companies Act 2013</a></p>
                      <p class="navla"><a class="dropdown-item" target="_blank" href="http://www.mca.gov.in/MinistryV2/insolvency+and+bankruptcy+code.html" style="color:white; font-size:14px">Insolvency and Bankruptcy Code. 2016</a></p>
                      <p class="navla"><a class="dropdown-item" target="_blank" href="http://www.mca.gov.in/MinistryV2/competitionact.html" style="color:white; font-size:14px;">Companies Act,2002</a></p>
                      <p class="navla"><a class="dropdown-item" target="_blank" href="http://www.mca.gov.in/MinistryV2/partnershipact.html"style="color:white; font-size:14px">Patnership Act,1932</a></p>
                      <p class="navla"><a class="dropdown-item" target="_blank" href="http://www.mca.gov.in/MinistryV2/llpact.html" style="color:white; font-size:14px">Limited Liability Partnership Act. 2008</a></p>
                      <p class="navla"><a class="dropdown-item" target="_blank" href="http://www.mca.gov.in/MinistryV2/charteredaccountantsact.html"style="color:white; font-size:14px">Chartered Accountants Act,1949</a></p>
                      <p class="navla"><a class="dropdown-item" target="_blank" href="http://www.mca.gov.in/MinistryV2/costandworksact.html" style="color:white; font-size:14px">Cost and Works Accountants Act,1959</a></p>
                      <p class="navla"><a class="dropdown-item" target="_blank" href="http://www.mca.gov.in/MinistryV2/thecompanysecretariesact.html" style="color:white; font-size:14px">Company Secretaries Act,1980</a></p>
                      <p class="navla"><a class="dropdown-item" target="_blank" href="http://www.mca.gov.in/MinistryV2/societiesregistrationact.html"style="color:white; font-size:14px">Societies Registration Act,1860</a></p>
                      <p class="navla"><a class="dropdown-item" target="_blank" href="http://www.mca.gov.in/MinistryV2/companiesdonationtonationalfundact1951.html"style="color:white; font-size:14px">Company (Donation to National) Fund Act, 1951</a></p>
                      <p class="navla"><a class="dropdown-item" target="_blank" href="http://www.mca.gov.in/MinistryV2/othercirculars.html"style="color:white; font-size:14px">Other Circulars</a></p>
                      </div>
                  </li>
                  <li><a href="{% url 'index' %}#link">Links</a></li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Services <i class="fa fa-caret-down"></i>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown" style ="background-color:#6e727a; width: 300px" >
                      <p class="navla"><a class="dropdown-item" href="{% url "front:new1" %}" style="color:white; font-size:14px;">Companies Act 2013</a></p>
                      <p class="navla"><a class="dropdown-item" href="{% url "front:new2" %}" style="color:white; font-size:14px">National Company Law Tribunal Services</a></p>
                      <p class="navla"><a class="dropdown-item" href="{% url "front:new3" %}" style="color:white; font-size:14px;">Foreign Exchange Management Act. 1999[FEMA]</a></p>
                      <p class="navla"><a class="dropdown-item" href="{% url "front:new4" %}"style="color:white; font-size:14px">Foreign Contribution (Regulation) Act. 2010</a></p>
                      <p class="navla"><a class="dropdown-item" href="{% url "front:new5" %}" style="color:white; font-size:14px">Limited Liability Partnership Act. 2008</a></p>
                      <p class="navla"><a class="dropdown-item" href="{% url "front:new10" %}"style="color:white; font-size:14px">Intellectual Property Rights</a></p>
                      <p class="navla"><a class="dropdown-item" href="{% url "front:new7" %}" style="color:white; font-size:14px">SEBI and Securities Laws</a></p>
                      <p class="navla"><a class="dropdown-item" href="{% url "front:new8" %}" style="color:white; font-size:14px">Auditing and Taxation</a></p>
                      <p class="navla"><a class="dropdown-item" href="{% url "front:new9" %}"style="color:white; font-size:14px">Other Services</a></p>
                      </div>
                  </li>
                  <li><a href="{% url 'Search_Company:search_company' %}" target="_blank">Search Company</a></li>
                  <li><a href="{% url 'index' %}#about"#about">About Us</a></li>
                  <li><a href="{% url 'index' %}#contact"#contact">Contact</a></li>
                   <li class="login"><a href="#" data-target="#selectid" data-toggle="modal">ADMIN</a></li>
                   <li class="login"><a href="{% url "EmployeeDashboard:emp_auth" %}">EMPLOYEE</a>
                   </li>

                </ul>

              </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
          </nav>
      <div class="modal fade" id="selectid" role="dialog">
         <div class="modal-dialog modal-sm">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title">Admin verification</h4>
            </div>
            <div class="modal-body">
              <form id="newModalForm">
                <label for="admin_id">Admin ID:</label>
                <input type="text"  id="admin_id" name="admin_id" placeholder="Enter admin id" />
              </form>
            </div>
            <div class="modal-footer">
              <a href="#" data-target="" data-toggle="modal" id ="modal1">
              <button type="button" class="btn btn-success btn-sm" id="btnSaveIt">Submit</button>
            </a>
            </div>
          </div>
        </div>
      </div>



      <div class="modal fade" id="select" role="dialog">
        <div class="modal-dialog modal-md">

          <!-- Modal content no 1-->
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title text-center form-title">Register / Login</h4>
            </div>
            <div class="modal-body padtrbl">

              <div class="modal-body">
               <div class="col-md-6">
                 <center>
                  <a href="{% url 'AdminDashboard:reg' %}"  role="button" class="btn btn-primary" title="Register">Register</a></center>
                 </div>
                 <div class="col-md-6">
                   <center>
                     <a href="{% url 'AdminDashboard:user_login' %}" role="button" class="btn btn-success" title="Login">Login</a></center>
                   </div>
                 </div>
                 <hr>
               </div>
             </div>
           </div>
         </div>
         <!--/ Register/Login-->

         {% block body_block %}
         <!--   your content goes here... -->

         {% endblock %}




         
<!--Footer-->
<footer id="footer" class="footer" style="background:black; padding-bottom:120px;">
  <div class="container">
    <div class="footer-wrapper">
      <div class="copyright">
        <p style="color:white">© Copyright 2018. All Rights Reserved. </p>
      </div>
    </div>
  </div>
</footer>


<div class="scrollup">
  <a href="#"><i class="fa fa-chevron-up"></i></a>
</div>


<script src="{% static "assets/js/vendor/jquery-1.11.2.min.js" %}"></script>
<script src="{% static "assets/js/vendor/bootstrap.min.js" %}"></script>

<script src="{% static "assets/js/plugins.js" %}"></script>
<script src="{% static "assets/js/modernizr.js" %}"></script>
<script src="{% static "assets/js/main.js" %}"></script>
</body>

front/templates/new1.html
{% extends "base.html" %}
{% block body_block %}

      
   <div class="container"  height="100%">
    <div class="jumbotron">
		<h2>COMPANY ACT,2013</h2>
		  <p>
		    <ul class="list-unstyled">
		       <li><h4>* Incorporation of companies (Private, Public, Section 8, NBFCs or any other kind).</h4></li>
               <li><h4>* Shifting of Registered Office of the Company.</h4></li>
           	   <li><h4>* Compounding of Offenses.</h4></li>
	           <li><h4>* Removal of auditor and/ or director.</h4></li>
	           <li><h4>* Condonation of delay.</h4></li>
	           <li><h4>* Secretarial Audit and/or Due Diligence.</h4></li>
	           <li><h4>* Fast Track Merger under Section 233 of the Companies Act, 2013.</h4></li>
         	   <li><h4>* Striking-off the companies under Fast Track Exit Scheme.</h4></li>
	           <li><h4>* Maintenance of Statutory Records and Annual Compliances under the Companies Act, 2013.</h4></li>
	           <li><h4>* Advisory on various issues relating to the Companies Act, 2013.</h4></li>
	           <li><h4>* Any other assignment.</li>
		    </ul>
		  </p>
      </div>
	</div>
  <br><br>
{% endblock %}		      

front/templates/new10.html
{% extends "base.html" %}
{% block body_block %}

	<div class="container">
    <div class="jumbotron">
	    <h2>Intellectual Property Rights</h2>
		  <p>
		    <ul>
		     <li><h4>* Registration and Renewal of Trademark, Copy Rights, Patents and other IPRs.</h4></li>
             <li><h4>* Other related Services</h4></li>
		    </ul>
		  </p>
      </div><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
	</div>

	        
	
{% endblock %}

front/templates/new2.html
{% extends "base.html" %}
{% block body_block %}

<div class="container">
    <div class="jumbotron">
		<h2>NATIONAL COMPANY LAW TRIBUNAL SERVICES</h2>
		  <p>
		    <ul>
		     <li><h4>* Change in Financial Year of the Company.</h4></li>
        	 <li><h4>* Conversion of Public Limited Company into Private Limited Company.</h4></li>
	         <li><h4>* Share Transfer/Registration Disputes under Section 58 and 59 of the Companies Act, 2013.</h4></li>
	         <li><h4>* Oppression and Mismanagement under Section 241 of the Companies Act, 2013.</h4></li>
	         <li><h4>* Merger/Amalgamation, Demerger or any other kind of restructuring.</h4></li>
	         <li><h4>* Winding-up of the companies.</h4></li>
	         <li><h4>* Appeal to NATIONAL COMPANY LAW APPELLATE TRIBUNALS.</h4></li>
 	         <li><h4>* Any other assignments.</h4></li>
		    </ul>
		  </p>
      </div><br><br><br><br><br><br><br>
	</div>
		        
{% endblock %}  	

front/templates/new3.html
{% extends "base.html" %}
{% block body_block %}

   <div class="container">
    <div class="jumbotron">
	  <h2>FOREIGN EXCHANGE MANAGEMENT ACT. 1999[FEMA]</h2>
		  <p>
		    <ul>
		     <li><h4>* Advance Reporting on Foreign Inward Remittance</h4></li>
	         <li><h4>* Filing of Form FC-GPR with the Reserve Bank of India.</h4></li>
	         <li><h4>* Filing of Foreign Liabilities and Assets Return.</h4></li>
      	     <li><h4>* Assistance in Foreign Collaboration and Joint Ventures.</h4></li>
	         <li><h4>* Other Compliances under FEMA.</li>
		    </ul>
		  </p>
      </div>
	</div><br><br><br><br><br><br><br><br><br><br><br><br>
		       
{% endblock %}  
	

front/templates/new4.html
{% extends "base.html" %}
{% block body_block %}

	<div class="container">
    <div class="jumbotron">
		<h2>FOREIGN CONTRIBUTION (REGULATION) ACT. 2010</h2>
		  <p>
		    <ul>
			  <li><h4>* Obtaining of Certificate of Registration/Prior Permissions.</h4></li>
 	          <li><h4>* Renewal of Certificate of Registration.</h4></li>
	          <li><h4>* Other Advisory and Compliances.</h4></li>
		    </ul>
		  </p>
      </div>
	</div><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
		       
{% endblock %}

front/templates/new5.html
{% extends "base.html" %}
{% block body_block %}

	<div class="container">
    <div class="jumbotron">
		<h2>LIMITED LIABILITY PARTNERSHIP ACT, 2008</h2>
		  <p>
		    <ul>
		     <li><h4>* Registration & other necessary compliances with respect to LLP.</h4></li>
	         <li><h4>* Drafting of LLP agreements.</h4></li>
	         <li><h4>* Conversion of Private/Public Company into Limited Liability Partnership.</h4></li>
	         <li><h4>* Conversion Partnership Firm into Limited Liability Partnership.</h4></li>
	         <li><h4>* Other Compliances.</h4></li>
		    </ul>
		  </p>
      </div><br><br><br><br><br><br><br><br><br><br><br><br>
	</div>
		        
{% endblock %}

front/templates/new7.html
{% extends "base.html" %}
{% block body_block %}

	<div class="container">
    <div class="jumbotron">
	    <h2>SEBI & SECURITIES LAWS</h2>
		  <p>
		    <ul>
		     <li><h4>* Listing of Securities of a Company with NSE, BSE and other Recognized Stock Exchanges</h4></li>
	         <li><h4>* SME listing</h4></li>
	         <li><h4>* Advisory Services for various Compliances to be made under Listing Agreement, LODR, etc.</h4></li>
	         <li><h4>* Corporate Governance Audit.</h4></li>
	         <li><h4>* Initial Public Offer or Public Issue.</h4></li>
	         <li><h4>* Any other assignment.</h4></li>
		    </ul>
		  </p>
      </div><br><br><br><br><br><br><br><br><br><br>
	</div>

{% endblock %}    

front/templates/new8.html
{% extends "base.html" %}
{% block body_block %}

	<div class="container">
    <div class="jumbotron">
	   <h2>AUDITING & TAXATION</h2>
		  <p>
		    <ul>
		     <li><h4>* Conducting Statutory Audit of the companies.</h4></li>
	         <li><h4>* Book-keeping.</h4></li>
	         <li><h4>* All kind of taxation matters.</h4></li>
	         <li><h4>* Any other assignment.</h4></li>
		    </ul>
		  </p>
      </div><br><br><br><br><br><br><br><br><br><br><br><br><br>
	</div>
		       
{% endblock %}	